package com.fitouts.roomcollab.domain;

public enum RoomTaskType {
    DESIGN,
    CONCEPT_MOODBOARD,
    LAYOUT_PLAN,
    THREE_D_RENDER,
    TILE_SELECTION,
    FLOORING_SELECTION,
    PAINT_COLOR,
    WALLPAPER,
    JOINERY,
    KITCHEN,
    WARDROBE,
    BATHROOM_FITTINGS,
    LIGHTING,
    ELECTRICAL_POINTS,
    AC_LOCATION,
    CURTAINS_BLINDS,
    FURNITURE,
    MATERIAL,
    SAMPLE_APPROVAL,
    MEASUREMENT_CONFIRMATION,
    CHANGE_ORDER,
    OTHER,
    CUSTOM
}
