-- Seed BOQ work item masters and catalog from Docs/boq_data.json (idempotent per company).

INSERT INTO work_item_masters (company_id, name, code)
SELECT c.uuid, v.name, v.code
FROM companies c
CROSS JOIN (VALUES
    ('APPROVALS & DRAWINGS', 'A'),
    ('PRELIMINARIES', 'B'),
    ('DEMOLITION WORK', 'C'),
    ('BUILDING WORKS', 'D'),
    ('FLOOR & WALL CLADDING', 'E'),
    ('CEILING WORKS', 'F'),
    ('PAINTING WORKS', 'G'),
    ('PLUMBING WORKS', 'H'),
    ('ELECTRICAL WORKS', 'I'),
    ('EXHAUST & A/C WORKS', 'J'),
    ('JOINERY WORKS', 'K')
) AS v(name, code)
ON CONFLICT (company_id, code) DO NOTHING;

INSERT INTO work_items (
    company_id,
    work_item_master_id,
    work_item_name,
    work_item_code,
    description,
    unit_type,
    default_rate,
    cost_price,
    selling_price_override,
    cost_price_override,
    quantity_formula_type,
    ceiling_applicable,
    wall_applicable,
    floor_applicable,
    active,
    deleted
)
SELECT
    c.uuid,
    wim.id,
    v.work_item_name,
    v.work_item_code,
    v.description,
    v.unit_type,
    v.default_rate,
    v.cost_price,
    FALSE,
    CASE WHEN v.default_rate IS NULL THEN FALSE ELSE TRUE END,
    'MANUAL',
    FALSE,
    FALSE,
    FALSE,
    TRUE,
    FALSE
FROM companies c
CROSS JOIN (VALUES
    ( 'A', 'A.1', '2D Floor Plans and Spatial arrangements including preparation of drawings as required from Developer (EMAAR)', '2D Floor Plans and Spatial arrangements including preparation of drawings as required from Developer (EMAAR)', 'LOT', NULL , NULL ),
    ( 'A', 'A.2', 'Submissions of approved layouts to obtain NOC and Completion Certificates including coordination, appointments, visits and site inspections to Developer (EMAAR)', 'Submissions of approved layouts to obtain NOC and Completion Certificates including coordination, appointments, visits and site inspections to Developer (EMAAR)', 'PCS', 2500.00 , 2500.00 ),
    ( 'A', 'A.3', 'Detailed 2D shop drawings for project execution (2 revisions) accompanied by an exhaustive list detailing the necessary materials such as tiles, sanitary fixtures, sink & accessories for constructi...', 'Detailed 2D shop drawings for project execution (2 revisions) accompanied by an exhaustive list detailing the necessary materials such as tiles, sanitary fixtures, sink & accessories for construction at:', 'LOT', NULL , NULL ),
    ( 'A', 'A.4', 'Sketchup 3D illustrations (2 revisions - 2views/area)', 'Sketchup 3D illustrations (2 revisions - 2views/area)', 'LOT', NULL , NULL ),
    ( 'A', 'A.4-2', 'Preparation of Architectural Drawings for maid''s room and living area extension works  as required from Dubai Municipality as follows:', 'Preparation of Architectural Drawings for maid''s room and living area extension works  as required from Dubai Municipality as follows:', 'LOT', NULL , NULL ),
    ( 'A', 'A.5', 'Submission of Architectural Design drawings package to Dubai Municipality to obtain building permit including application for Completion Certificates, coordination, appointments & site inspections', 'Submission of Architectural Design drawings package to Dubai Municipality to obtain building permit including application for Completion Certificates, coordination, appointments & site inspections', 'PCS', 1200.00 , 1200.00 ),
    ( 'A', 'A.4-3', 'Preparation of Structural and Architectural Design Drawings for extension (FF) works  to be developed as required from Dubai Municipality / Dubai Development Authority .', 'Preparation of Structural and Architectural Design Drawings for extension (FF) works  to be developed as required from Dubai Municipality / Dubai Development Authority .', 'PCS', 28500.00 , 28500.00 ),
    ( 'A', 'A.5-2', 'Submission of Design drawings package to Dubai Municipality / Dubai Development Authority to obtain building permit  including application for Completion Certificates, coordination, appointments & ...', 'Submission of Design drawings package to Dubai Municipality / Dubai Development Authority to obtain building permit  including application for Completion Certificates, coordination, appointments & site inspections', 'PCS', 6250.00 , 6250.00 ),
    ( 'A', 'A.6', 'Provisional amount preparation of MEP Design due to extension work to be developed as required from Dubai Municipality / Dubai Development Authority', 'Provisional amount preparation of MEP Design due to extension work to be developed as required from Dubai Municipality / Dubai Development Authority', 'LOT', NULL , NULL ),
    ( 'B', 'B.1', 'Site mobilization and protection', 'Site mobilization and protection', 'PCS', 4875.00 , 4875.00 ),
    ( 'B', 'B.2', 'Project site coordination, site supervision and quality management', 'Project site coordination, site supervision and quality management', 'PCS', 18750.00 , 18750.00 ),
    ( 'B', 'B.3', 'Preparation and monitoring of detailed works schedule outlining all project tasks according to the final scope', 'Preparation and monitoring of detailed works schedule outlining all project tasks according to the final scope', 'PCS', 2250.00 , 2250.00 ),
    ( 'B', 'B.4', 'Health & Safety measures in compliance with UAE rules & regulations. Personal Protective Equipment (PPE) and awareness of risks and hazards on site', 'Health & Safety measures in compliance with UAE rules & regulations. Personal Protective Equipment (PPE) and awareness of risks and hazards on site', 'PCS', 2625.00 , 2625.00 ),
    ( 'B', 'B.5', 'Contractor''s All Risk (CAR) Insurance', 'Contractor''s All Risk (CAR) Insurance', 'LOT', NULL , NULL ),
    ( 'B', 'B.6', 'Day-to-day site cleaning to comply with authority health and safety requirement and final construction cleaning prior to handing over', 'Day-to-day site cleaning to comply with authority health and safety requirement and final construction cleaning prior to handing over', 'PCS', 4125.00 , 4125.00 ),
    ( 'B', 'B.7', 'Deep cleaning of the Villa before Client moves in', 'Deep cleaning of the Villa before Client moves in', 'PCS', 2850.00 , 2850.00 ),
    ( 'C', 'C.1', 'Removal of existing skirting in all areas (GF)', 'Removal of existing skirting in all areas (GF)', 'RMT', 15.00 , 15.00 ),
    ( 'C', 'C.2', 'Removal of existing kitchen cabinets and counter tops, demolition of wall tiles and false ceiling at kitchen area', 'Removal of existing kitchen cabinets and counter tops, demolition of wall tiles and false ceiling at kitchen area', 'PCS', 1200.00 , 1200.00 ),
    ( 'C', 'C.3', 'Removal of existing door leaf, architraves and frame at', 'Removal of existing door leaf, architraves and frame at', 'PCS', 250.00 , 250.00 ),
    ( 'C', 'C.4', 'Removal of existing aluminum door/window at:', 'Removal of existing aluminum door/window at:', 'LOT', NULL , NULL ),
    ( 'C', 'C.5', 'Demolition of existing external block wall', 'Demolition of existing external block wall', 'LOT', NULL , NULL ),
    ( 'C', 'C.6', 'Demolition of full height internal block wall at:', 'Demolition of full height internal block wall at:', 'LOT', NULL , NULL ),
    ( 'C', 'C.6.a', 'XXX', 'Demolition of full height internal block wall at: — XXX', 'PCS', 0.00 , 0.00 ),
    ( 'C', 'C.7', 'Demolition of 2.2m width by 1.2m height block wall between dining and kitchen', 'Demolition of 2.2m width by 1.2m height block wall between dining and kitchen', 'PCS', 0.00 , 0.00 ),
    ( 'C', 'C.8', 'Removal of existing sanitary fixtures, bathroom accessories, architrave (internal side), demolition of floor tiles, screed, wall tiles & false ceiling at:', 'Removal of existing sanitary fixtures, bathroom accessories, architrave (internal side), demolition of floor tiles, screed, wall tiles & false ceiling at:', 'LOT', NULL , NULL ),
    ( 'C', 'C.8.a', 'Powder Room', 'Removal of existing sanitary fixtures, bathroom accessories, architrave (internal side), demolition of floor tiles, screed, wall tiles & false ceiling at: — Powder Room', 'PCS', 350.00 , 350.00 ),
    ( 'C', 'C.8.b', 'Maid''s Bathroom', 'Removal of existing sanitary fixtures, bathroom accessories, architrave (internal side), demolition of floor tiles, screed, wall tiles & false ceiling at: — Maid''s Bathroom', 'PCS', 450.00 , 450.00 ),
    ( 'C', 'C.8.c', 'Guest Bathroom', 'Removal of existing sanitary fixtures, bathroom accessories, architrave (internal side), demolition of floor tiles, screed, wall tiles & false ceiling at: — Guest Bathroom', 'PCS', 450.00 , 450.00 ),
    ( 'C', 'C.9', 'Removal of existing balustrade at staircase', 'Removal of existing balustrade at staircase', 'PCS', 590.00 , 590.00 ),
    ( 'C', 'C.10', 'Demolition of existing marble step, riser, landing and skirting at staircase', 'Demolition of existing marble step, riser, landing and skirting at staircase', 'PCS', 3100.00 , 3100.00 ),
    ( 'C', 'C.11', 'Demolition of existing floor tiles, screed & skirting at:', 'Demolition of existing floor tiles, screed & skirting at:', 'LOT', NULL , NULL ),
    ( 'C', 'C.11.a', 'Patio', 'Demolition of existing floor tiles, screed & skirting at: — Patio', 'PCS', 0.00 , 0.00 ),
    ( 'C', 'C.11.b', 'Terrace', 'Demolition of existing floor tiles, screed & skirting at: — Terrace', 'PCS', 0.00 , 0.00 ),
    ( 'C', 'C.12', 'Demolition of false ceiling at:', 'Demolition of false ceiling at:', 'LOT', NULL , NULL ),
    ( 'C', 'C.12.a', 'XXX', 'Demolition of false ceiling at: — XXX', 'PCS', 0.00 , 0.00 ),
    ( 'C', 'C.7-2', 'Demolition of existing boundary wall', 'Demolition of existing boundary wall', 'LOT', NULL , NULL ),
    ( 'C', 'C.13', 'Removal of existing skirting in all areas (FF)', 'Removal of existing skirting in all areas (FF)', 'RMT', 15.00 , 15.00 ),
    ( 'C', 'C.14', 'Removal of existing door leaf, architraves and frame at', 'Removal of existing door leaf, architraves and frame at', 'PCS', 250.00 , 250.00 ),
    ( 'C', 'C.15', 'Removal of existing sanitary fixtures and bathroom accessories, architrave (internal side only), demolition of floor tiles, screeding, wall tiles and false ceiling at:', 'Removal of existing sanitary fixtures and bathroom accessories, architrave (internal side only), demolition of floor tiles, screeding, wall tiles and false ceiling at:', 'LOT', NULL , NULL ),
    ( 'C', 'C.15.a', 'Common Bathroom', 'Removal of existing sanitary fixtures and bathroom accessories, architrave (internal side only), demolition of floor tiles, screeding, wall tiles and false ceiling at: — Common Bathroom', 'PCS', 450.00 , 450.00 ),
    ( 'C', 'C.15.b', 'Bathroom 1', 'Removal of existing sanitary fixtures and bathroom accessories, architrave (internal side only), demolition of floor tiles, screeding, wall tiles and false ceiling at: — Bathroom 1', 'PCS', 450.00 , 450.00 ),
    ( 'C', 'C.15.c', 'Master Bathroom', 'Removal of existing sanitary fixtures and bathroom accessories, architrave (internal side only), demolition of floor tiles, screeding, wall tiles and false ceiling at: — Master Bathroom', 'PCS', 550.00 , 550.00 ),
    ( 'C', 'C.16', 'Demolition of 0.6m width by full height wall at master bathroom', 'Demolition of 0.6m width by full height wall at master bathroom', 'PCS', 410.00 , 410.00 ),
    ( 'C', 'C.17', 'Demolition of existing floor tiles, screed & skirting at:', 'Demolition of existing floor tiles, screed & skirting at:', 'LOT', NULL , NULL ),
    ( 'C', 'C.17.a', 'Balcony 1', 'Demolition of existing floor tiles, screed & skirting at: — Balcony 1', 'PCS', 0.00 , 0.00 ),
    ( 'C', 'C.17.b', 'Master Balcony', 'Demolition of existing floor tiles, screed & skirting at: — Master Balcony', 'PCS', 0.00 , 0.00 ),
    ( 'C', 'C.18', 'Carting away the debris to approved Dubai municipal dump yards', 'Carting away the debris to approved Dubai municipal dump yards', 'PCS', 2790.00 , 2790.00 ),
    ( 'D', 'D.1', 'Repair of surfaces where the skirting was removed', 'Repair of surfaces where the skirting was removed', 'RMT', 15.00 , 15.00 ),
    ( 'D', 'D.2', 'Repair and surface preparation of walls to receive the new backsplash tiles at kitchen', 'Repair and surface preparation of walls to receive the new backsplash tiles at kitchen', 'RMT', 70.00 , 70.00 ),
    ( 'D', 'D.3', 'Repair of surfaces where the wall was demolished at:', 'Repair of surfaces where the wall was demolished at:', 'LOT', NULL , NULL ),
    ( 'D', 'D.3.a', 'XXX', 'Repair of surfaces where the wall was demolished at: — XXX', 'PCS', 790.00 , 790.00 ),
    ( 'D', 'D.4', 'Repair of surface after removal of sliding door to allow the installation of new doors at Living Area', 'Repair of surface after removal of sliding door to allow the installation of new doors at Living Area', 'LOT', NULL , NULL ),
    ( 'D', 'D.5', 'Construction of wall cladding to conceal the WC cistern from floor to ceiling at:', 'Construction of wall cladding to conceal the WC cistern from floor to ceiling at:', 'LOT', NULL , NULL ),
    ( 'D', 'D.5.a', 'Powder Room - 0.80m width', 'Construction of wall cladding to conceal the WC cistern from floor to ceiling at: — Powder Room - 0.80m width', 'PCS', 350.00 , 350.00 ),
    ( 'D', 'D.5.b', 'Guest Bathroom - 0.80m width', 'Construction of wall cladding to conceal the WC cistern from floor to ceiling at: — Guest Bathroom - 0.80m width', 'PCS', 350.00 , 350.00 ),
    ( 'D', 'D.6', 'Construction of  0.80m width wall to conceal the WC cistern, to build  a 60cm wide x 30cm high and a 20cm wide x 60cm high niches at office bathroom', 'Construction of  0.80m width wall to conceal the WC cistern, to build  a 60cm wide x 30cm high and a 20cm wide x 60cm high niches at office bathroom', 'PCS', 380.00 , 380.00 ),
    ( 'D', 'D.7', 'Supply and installation of 25cm thick Thermal Block with 6cm extruded polystyrene insert including mortar and both sides plastering at:', 'Supply and installation of 25cm thick Thermal Block with 6cm extruded polystyrene insert including mortar and both sides plastering at:', 'LOT', NULL , NULL ),
    ( 'D', 'D.7.a', 'XXX', 'Supply and installation of 25cm thick Thermal Block with 6cm extruded polystyrene insert including mortar and both sides plastering at: — XXX', 'LOT', 395.00 , 395.00 ),
    ( 'D', 'D.8', 'Construction of concrete beam to allow installation of new door/window at:', 'Construction of concrete beam to allow installation of new door/window at:', 'LOT', NULL , NULL ),
    ( 'D', 'D.8.a', 'XXX', 'Construction of concrete beam to allow installation of new door/window at: — XXX', 'PCS', 0.00 , 0.00 ),
    ( 'D', 'D.9', 'Construction of full height internal wall at:', 'Construction of full height internal wall at:', 'LOT', NULL , NULL ),
    ( 'D', 'D.10', 'Repair and surface preparation of walls to receive the wall tiles at:', 'Repair and surface preparation of walls to receive the wall tiles at:', 'LOT', NULL , NULL ),
    ( 'D', 'D.10.a', 'Powder Room', 'Repair and surface preparation of walls to receive the wall tiles at: — Powder Room', 'LOT', 70.00 , 70.00 ),
    ( 'D', 'D.10.b', 'Maid''s Bathroom', 'Repair and surface preparation of walls to receive the wall tiles at: — Maid''s Bathroom', 'LOT', 70.00 , 70.00 ),
    ( 'D', 'D.10.c', 'Guest Bathroom', 'Repair and surface preparation of walls to receive the wall tiles at: — Guest Bathroom', 'LOT', 70.00 , 70.00 ),
    ( 'D', 'D.11', 'Supply and application of liquid applied waterproofing (Mapei Mapelastic) with mesh to floor, full height in shower area  (if any) & 300mm height to rest of wall perimeter at:', 'Supply and application of liquid applied waterproofing (Mapei Mapelastic) with mesh to floor, full height in shower area  (if any) & 300mm height to rest of wall perimeter at:', 'LOT', NULL , NULL ),
    ( 'D', 'D.11.a', 'Powder Room', 'Supply and application of liquid applied waterproofing (Mapei Mapelastic) with mesh to floor, full height in shower area  (if any) & 300mm height to rest of wall perimeter at: — Powder Room', 'LOT', 130.00 , 130.00 ),
    ( 'D', 'D.11.b', 'Maid''s Bathroom', 'Supply and application of liquid applied waterproofing (Mapei Mapelastic) with mesh to floor, full height in shower area  (if any) & 300mm height to rest of wall perimeter at: — Maid''s Bathroom', 'LOT', 130.00 , 130.00 ),
    ( 'D', 'D.11.c', 'Guest Bathroom', 'Supply and application of liquid applied waterproofing (Mapei Mapelastic) with mesh to floor, full height in shower area  (if any) & 300mm height to rest of wall perimeter at: — Guest Bathroom', 'LOT', 130.00 , 130.00 ),
    ( 'D', 'D.12', 'Supply and application of 50mm thick (maximum) soft cement-sand leveled floor screeding ready to receive the floor tiles at:', 'Supply and application of 50mm thick (maximum) soft cement-sand leveled floor screeding ready to receive the floor tiles at:', 'LOT', NULL , NULL ),
    ( 'D', 'D.12.a', 'Powder Room', 'Supply and application of 50mm thick (maximum) soft cement-sand leveled floor screeding ready to receive the floor tiles at: — Powder Room', 'LOT', 75.00 , 75.00 ),
    ( 'D', 'D.12.b', 'Maid''s Bathroom', 'Supply and application of 50mm thick (maximum) soft cement-sand leveled floor screeding ready to receive the floor tiles at: — Maid''s Bathroom', 'LOT', 75.00 , 75.00 ),
    ( 'D', 'D.12.c', 'Guest Bathroom', 'Supply and application of 50mm thick (maximum) soft cement-sand leveled floor screeding ready to receive the floor tiles at: — Guest Bathroom', 'LOT', 75.00 , 75.00 ),
    ( 'D', 'D.13', 'Repair of surfaces after removal of marble step, riser and skirting at staircase', 'Repair of surfaces after removal of marble step, riser and skirting at staircase', 'PCS', 160.00 , 160.00 ),
    ( 'D', 'D.14', 'Chipping and repair of existing GF grade slab to allow the relocation of the drain points at:', 'Chipping and repair of existing GF grade slab to allow the relocation of the drain points at:', 'PCS', 395.00 , 395.00 ),
    ( 'D', 'D.15', 'Construction of balustrade wall by cutting the existing marble by 10cm at edge and installation of  solid blocks with necessary steel reinforcement at staircase area', 'Construction of balustrade wall by cutting the existing marble by 10cm at edge and installation of  solid blocks with necessary steel reinforcement at staircase area', 'RMT', 800.00 , 800.00 ),
    ( 'D', 'D.16', 'Construction of staircase step extension - 1.0m width', 'Construction of staircase step extension - 1.0m width', 'PCS', 530.00 , 530.00 ),
    ( 'D', 'D.16-2', 'Repair of surfaces where the skirting was removed', 'Repair of surfaces where the skirting was removed', 'RMT', 15.00 , 15.00 ),
    ( 'D', 'D.17', 'Construction of width wall cladding to conceal the WC cistern from floor to ceiling at:', 'Construction of width wall cladding to conceal the WC cistern from floor to ceiling at:', 'LOT', NULL , NULL ),
    ( 'D', 'D.17.a', 'Common bathroom - 0.80m width', 'Construction of width wall cladding to conceal the WC cistern from floor to ceiling at: — Common bathroom - 0.80m width', 'PCS', 350.00 , 350.00 ),
    ( 'D', 'D.17.a-2', 'Common bathroom - 0.80m width', 'Construction of width wall cladding to conceal the WC cistern from floor to ceiling at: — Common bathroom - 0.80m width', 'PCS', 350.00 , 350.00 ),
    ( 'D', 'D.17.b', 'Master bathroom - 0.80m width', 'Construction of width wall cladding to conceal the WC cistern from floor to ceiling at: — Master bathroom - 0.80m width', 'PCS', 350.00 , 350.00 ),
    ( 'D', 'D.18', 'Repair and surface preparation of walls to receive the wall tiles at:', 'Repair and surface preparation of walls to receive the wall tiles at:', 'LOT', NULL , NULL ),
    ( 'D', 'D.18.a', 'Common Bathroom', 'Repair and surface preparation of walls to receive the wall tiles at: — Common Bathroom', 'LOT', 70.00 , 70.00 ),
    ( 'D', 'D.18.b', 'Bathroom 1', 'Repair and surface preparation of walls to receive the wall tiles at: — Bathroom 1', 'LOT', 70.00 , 70.00 ),
    ( 'D', 'D.18.c', 'Master Bathroom', 'Repair and surface preparation of walls to receive the wall tiles at: — Master Bathroom', 'LOT', 70.00 , 70.00 ),
    ( 'D', 'D.19', 'Supply and application of liquid applied waterproofing (Mapei Mapelastic) with mesh to floor, full height in shower area  (if any) & 300mm height to rest of wall perimeter at:', 'Supply and application of liquid applied waterproofing (Mapei Mapelastic) with mesh to floor, full height in shower area  (if any) & 300mm height to rest of wall perimeter at:', 'LOT', NULL , NULL ),
    ( 'D', 'D.19.a', 'Common Bathroom', 'Supply and application of liquid applied waterproofing (Mapei Mapelastic) with mesh to floor, full height in shower area  (if any) & 300mm height to rest of wall perimeter at: — Common Bathroom', 'LOT', 130.00 , 130.00 ),
    ( 'D', 'D.19.b', 'Bathroom 1', 'Supply and application of liquid applied waterproofing (Mapei Mapelastic) with mesh to floor, full height in shower area  (if any) & 300mm height to rest of wall perimeter at: — Bathroom 1', 'LOT', 130.00 , 130.00 ),
    ( 'D', 'D.19.c', 'Master Bathroom', 'Supply and application of liquid applied waterproofing (Mapei Mapelastic) with mesh to floor, full height in shower area  (if any) & 300mm height to rest of wall perimeter at: — Master Bathroom', 'LOT', 130.00 , 130.00 ),
    ( 'D', 'D.20', 'Supply and application of 50mm thick (maximum) soft cement-sand leveled floor screeding ready to receive the floor tiles at:', 'Supply and application of 50mm thick (maximum) soft cement-sand leveled floor screeding ready to receive the floor tiles at:', 'LOT', NULL , NULL ),
    ( 'D', 'D.20.a', 'Common Bathroom', 'Supply and application of 50mm thick (maximum) soft cement-sand leveled floor screeding ready to receive the floor tiles at: — Common Bathroom', 'LOT', 75.00 , 75.00 ),
    ( 'D', 'D.20.b', 'Bathroom 1', 'Supply and application of 50mm thick (maximum) soft cement-sand leveled floor screeding ready to receive the floor tiles at: — Bathroom 1', 'LOT', 75.00 , 75.00 ),
    ( 'D', 'D.20.c', 'Master Bathroom', 'Supply and application of 50mm thick (maximum) soft cement-sand leveled floor screeding ready to receive the floor tiles at: — Master Bathroom', 'LOT', 75.00 , 75.00 ),
    ( 'D', 'D.21', 'Coring required of new drain points for wash basin, WC, shower, bathtub & floor drain at master bathroom', 'Coring required of new drain points for wash basin, WC, shower, bathtub & floor drain at master bathroom', 'PCS', 465.00 , 465.00 ),
    ( 'D', 'D.22', 'Provisional amount for structural work at Extensions', 'Provisional amount for structural work at Extensions', 'LOT', NULL , NULL ),
    ( 'D', 'D.23', 'Supply and application of roof water proofing with 2 layers of 4mm thick SBS membrane at Roof Extension area', 'Supply and application of roof water proofing with 2 layers of 4mm thick SBS membrane at Roof Extension area', 'PCS', 0.00 , 0.00 ),
    ( 'D', 'D.24', 'Supply and installation of 25cm thick Thermal Block with 6cm extruded polystyrene insert including mortar and both sides plastering at:', 'Supply and installation of 25cm thick Thermal Block with 6cm extruded polystyrene insert including mortar and both sides plastering at:', 'LOT', NULL , NULL ),
    ( 'D', 'D.24.a', 'XXX', 'Supply and installation of 25cm thick Thermal Block with 6cm extruded polystyrene insert including mortar and both sides plastering at: — XXX', 'LOT', 395.00 , 395.00 ),
    ( 'D', 'D.25', 'Construction of concrete beam to allow installation of new door/window at:', 'Construction of concrete beam to allow installation of new door/window at:', 'LOT', NULL , NULL ),
    ( 'D', 'D.26', 'Construction of full height internal wall at:', 'Construction of full height internal wall at:', 'LOT', NULL , NULL ),
    ( 'E', 'E.1', 'Provisional amount for supply and application of 2-3mm self leveling to allow the installation of proposed SPC flooring', 'Provisional amount for supply and application of 2-3mm self leveling to allow the installation of proposed SPC flooring', 'LOT', NULL , NULL ),
    ( 'E', 'E.2', 'Provisional amount of supply and installation of 5mm thick Stone Plastic (or Polymer) Composite (SPC) with uniclick locking system at:', 'Provisional amount of supply and installation of 5mm thick Stone Plastic (or Polymer) Composite (SPC) with uniclick locking system at:', 'LOT', NULL , NULL ),
    ( 'E', 'E.3', 'Supply and installation of 10cm height - SL101 (Santa Luzia) White Matt skirting at:', 'Supply and installation of 10cm height - SL101 (Santa Luzia) White Matt skirting at:', 'LOT', NULL , NULL ),
    ( 'E', 'E.3.a', 'Ground Floor', 'Supply and installation of 10cm height - SL101 (Santa Luzia) White Matt skirting at: — Ground Floor', 'RMT', 85.00 , 85.00 ),
    ( 'E', 'E.3.b', 'First Floor', 'Supply and installation of 10cm height - SL101 (Santa Luzia) White Matt skirting at: — First Floor', 'RMT', 85.00 , 85.00 ),
    ( 'E', 'E.4', 'Installation only of  floor tiles with Mapei adhesive and grouting to match the tile color at:', 'Installation only of  floor tiles with Mapei adhesive and grouting to match the tile color at:', 'LOT', NULL , NULL ),
    ( 'E', 'E.4.a', 'Powder Room', 'Installation only of  floor tiles with Mapei adhesive and grouting to match the tile color at: — Powder Room', 'LOT', 95.00 , 95.00 ),
    ( 'E', 'E.4.b', 'Maid''s Bathroom', 'Installation only of  floor tiles with Mapei adhesive and grouting to match the tile color at: — Maid''s Bathroom', 'LOT', 95.00 , 95.00 ),
    ( 'E', 'E.4.c', 'Guest Bathroom', 'Installation only of  floor tiles with Mapei adhesive and grouting to match the tile color at: — Guest Bathroom', 'LOT', 95.00 , 95.00 ),
    ( 'E', 'E.4.d', 'Common Bathroom', 'Installation only of  floor tiles with Mapei adhesive and grouting to match the tile color at: — Common Bathroom', 'LOT', 95.00 , 95.00 ),
    ( 'E', 'E.4.e', 'Bathroom 1', 'Installation only of  floor tiles with Mapei adhesive and grouting to match the tile color at: — Bathroom 1', 'LOT', 95.00 , 95.00 ),
    ( 'E', 'E.4.f', 'Master Bathroom', 'Installation only of  floor tiles with Mapei adhesive and grouting to match the tile color at: — Master Bathroom', 'LOT', 95.00 , 95.00 ),
    ( 'E', 'E.5', 'Installation only of wall tiles (up to 2.4m height) with Mapei adhesive, grouting to match the tile color. Tile Size Considered: 60x60cm', 'Installation only of wall tiles (up to 2.4m height) with Mapei adhesive, grouting to match the tile color. Tile Size Considered: 60x60cm', 'LOT', NULL , NULL ),
    ( 'E', 'E.5.a', 'Powder Room', 'Installation only of wall tiles (up to 2.4m height) with Mapei adhesive, grouting to match the tile color. Tile Size Considered: 60x60cm — Powder Room', 'LOT', 100.00 , 100.00 ),
    ( 'E', 'E.5.b', 'Maid''s Bathroom', 'Installation only of wall tiles (up to 2.4m height) with Mapei adhesive, grouting to match the tile color. Tile Size Considered: 60x60cm — Maid''s Bathroom', 'LOT', 100.00 , 100.00 ),
    ( 'E', 'E.5.c', 'Guest Bathroom', 'Installation only of wall tiles (up to 2.4m height) with Mapei adhesive, grouting to match the tile color. Tile Size Considered: 60x60cm — Guest Bathroom', 'LOT', 100.00 , 100.00 ),
    ( 'E', 'E.5.d', 'Common Bathroom', 'Installation only of wall tiles (up to 2.4m height) with Mapei adhesive, grouting to match the tile color. Tile Size Considered: 60x60cm — Common Bathroom', 'LOT', 100.00 , 100.00 ),
    ( 'E', 'E.5.e', 'Bathroom 1', 'Installation only of wall tiles (up to 2.4m height) with Mapei adhesive, grouting to match the tile color. Tile Size Considered: 60x60cm — Bathroom 1', 'LOT', 100.00 , 100.00 ),
    ( 'E', 'E.5.f', 'Master Bathroom', 'Installation only of wall tiles (up to 2.4m height) with Mapei adhesive, grouting to match the tile color. Tile Size Considered: 60x60cm — Master Bathroom', 'LOT', 100.00 , 100.00 ),
    ( 'E', 'E.6', 'Cutting of tiles to 45 degrees at corner tiles at:', 'Cutting of tiles to 45 degrees at corner tiles at:', 'LOT', NULL , NULL ),
    ( 'E', 'E.6.a', 'Powder Room', 'Cutting of tiles to 45 degrees at corner tiles at: — Powder Room', 'RMT', 200.00 , 200.00 ),
    ( 'E', 'E.6.b', 'Maid''s Bathroom', 'Cutting of tiles to 45 degrees at corner tiles at: — Maid''s Bathroom', 'RMT', 200.00 , 200.00 ),
    ( 'E', 'E.6.c', 'Guest Bathroom', 'Cutting of tiles to 45 degrees at corner tiles at: — Guest Bathroom', 'RMT', 200.00 , 200.00 ),
    ( 'E', 'E.6.d', 'Common Bathroom', 'Cutting of tiles to 45 degrees at corner tiles at: — Common Bathroom', 'RMT', 200.00 , 200.00 ),
    ( 'E', 'E.6.e', 'Bathroom 1', 'Cutting of tiles to 45 degrees at corner tiles at: — Bathroom 1', 'RMT', 200.00 , 200.00 ),
    ( 'E', 'E.6.f', 'Master Bathroom', 'Cutting of tiles to 45 degrees at corner tiles at: — Master Bathroom', 'RMT', 200.00 , 200.00 ),
    ( 'E', 'E.7', 'Installation only of backsplash tiles with adhesive including grouting to match the tile color (from counter up to 0.60m height only) at kitchen area. Tile Size Considered: 60x60cm', 'Installation only of backsplash tiles with adhesive including grouting to match the tile color (from counter up to 0.60m height only) at kitchen area. Tile Size Considered: 60x60cm', 'RMT', 100.00 , 100.00 ),
    ( 'E', 'E.8', 'Supply and installation of aluminum profile at thresholds of doors or shower area at', 'Supply and installation of aluminum profile at thresholds of doors or shower area at', 'RMT', 250.00 , 250.00 ),
    ( 'E', 'E.9', 'Supply and installation of door marble threshold at Powder Room, Guest Bathroom, Common Bathroom, Bathroom 1 & Master Bathroom. Proposed Marble: Crema Marfil', 'Supply and installation of door marble threshold at Powder Room, Guest Bathroom, Common Bathroom, Bathroom 1 & Master Bathroom. Proposed Marble: Crema Marfil', 'RMT', 360.00 , 360.00 ),
    ( 'F', 'F.1', 'Supply and installation of new flat made of 1x12mm moisture resistant (MR-H2) gypsum board  including suspension system  with taping & jointing to be ready to receive the paint finish at:', 'Supply and installation of new flat made of 1x12mm moisture resistant (MR-H2) gypsum board  including suspension system  with taping & jointing to be ready to receive the paint finish at:', 'LOT', NULL , NULL ),
    ( 'F', 'F.1.a', 'Powder Room', 'Supply and installation of new flat made of 1x12mm moisture resistant (MR-H2) gypsum board  including suspension system  with taping & jointing to be ready to receive the paint finish at: — Powder Room', 'LOT', 195.00 , 195.00 ),
    ( 'F', 'F.1.b', 'Maid''s Bathroom', 'Supply and installation of new flat made of 1x12mm moisture resistant (MR-H2) gypsum board  including suspension system  with taping & jointing to be ready to receive the paint finish at: — Maid''s Bathroom', 'LOT', 195.00 , 195.00 ),
    ( 'F', 'F.1.c', 'Guest Bathroom', 'Supply and installation of new flat made of 1x12mm moisture resistant (MR-H2) gypsum board  including suspension system  with taping & jointing to be ready to receive the paint finish at: — Guest Bathroom', 'LOT', 195.00 , 195.00 ),
    ( 'F', 'F.1.d', 'Common Bathroom', 'Supply and installation of new flat made of 1x12mm moisture resistant (MR-H2) gypsum board  including suspension system  with taping & jointing to be ready to receive the paint finish at: — Common Bathroom', 'LOT', 195.00 , 195.00 ),
    ( 'F', 'F.1.e', 'Bathroom 1', 'Supply and installation of new flat made of 1x12mm moisture resistant (MR-H2) gypsum board  including suspension system  with taping & jointing to be ready to receive the paint finish at: — Bathroom 1', 'LOT', 195.00 , 195.00 ),
    ( 'F', 'F.1.f', 'Master Bathroom', 'Supply and installation of new flat made of 1x12mm moisture resistant (MR-H2) gypsum board  including suspension system  with taping & jointing to be ready to receive the paint finish at: — Master Bathroom', 'LOT', 195.00 , 195.00 ),
    ( 'F', 'F.1.g', 'Kitchen', 'Supply and installation of new flat made of 1x12mm moisture resistant (MR-H2) gypsum board  including suspension system  with taping & jointing to be ready to receive the paint finish at: — Kitchen', 'LOT', 195.00 , 195.00 ),
    ( 'F', 'F.1.h', 'other Areas', 'Supply and installation of new flat made of 1x12mm moisture resistant (MR-H2) gypsum board  including suspension system  with taping & jointing to be ready to receive the paint finish at: — other Areas', 'LOT', 195.00 , 195.00 ),
    ( 'F', 'F.2', 'Supply and installation of bulkhead made of 1x12mm moisture resistant (MR-H2) gypsum board including suspension system with taping & jointing ready to receive the paint finish at kitchen area where...', 'Supply and installation of bulkhead made of 1x12mm moisture resistant (MR-H2) gypsum board including suspension system with taping & jointing ready to receive the paint finish at kitchen area where the wall was demolished.', 'RMT', 195.00 , 195.00 ),
    ( 'F', 'F.3', 'Supply and installation of access panels at powder room, maid''s bathroom, common bathroom, master bathroom and kitchen.', 'Supply and installation of access panels at powder room, maid''s bathroom, common bathroom, master bathroom and kitchen.', 'LOT', NULL , NULL ),
    ( 'F', 'F.4', 'Supply and installation of 15cm dia circular diffusers at powder room, maid''s bathroom, common bathroom, master bathroom and kitchen.', 'Supply and installation of 15cm dia circular diffusers at powder room, maid''s bathroom, common bathroom, master bathroom and kitchen.', 'LOT', NULL , NULL ),
    ( 'F', 'F.5', 'Supply and installation of new flat false ceiling made of 1x12mm regular (RG) gypsum board including suspension system with taping & jointing ready to receive the paint finish at', 'Supply and installation of new flat false ceiling made of 1x12mm regular (RG) gypsum board including suspension system with taping & jointing ready to receive the paint finish at', 'LOT', 185.00 , 185.00 ),
    ( 'F', 'F.6', 'Supply and installation of new flat false ceiling + provision for coving made of 1x12mm regular (RG) gypsum board including suspension system with taping & jointing ready to receive the paint finis...', 'Supply and installation of new flat false ceiling + provision for coving made of 1x12mm regular (RG) gypsum board including suspension system with taping & jointing ready to receive the paint finish at', 'LOT', 245.00 , 245.00 ),
    ( 'G', 'G.1', 'Minor repair, supply and application of primer on walls & ceilings before application of final coat of paint at all internal areas', 'Minor repair, supply and application of primer on walls & ceilings before application of final coat of paint at all internal areas', 'PCS', 0.00 , 0.00 ),
    ( 'G', 'G.2', 'Supply and application of 2 layers of final coat of white Jotun fenomastic emulsion paint at internal areas', 'Supply and application of 2 layers of final coat of white Jotun fenomastic emulsion paint at internal areas', 'LOT', NULL , NULL ),
    ( 'G', 'G.2.a', 'Ground Floor - Internal Walls', 'Supply and application of 2 layers of final coat of white Jotun fenomastic emulsion paint at internal areas — Ground Floor - Internal Walls', 'LOT', 21.00 , 21.00 ),
    ( 'G', 'G.2.b', 'Ground Floor - Internal Ceilings', 'Supply and application of 2 layers of final coat of white Jotun fenomastic emulsion paint at internal areas — Ground Floor - Internal Ceilings', 'LOT', 23.00 , 23.00 ),
    ( 'G', 'G.2.c', 'First Floor - Internal Walls', 'Supply and application of 2 layers of final coat of white Jotun fenomastic emulsion paint at internal areas — First Floor - Internal Walls', 'LOT', 21.00 , 21.00 ),
    ( 'G', 'G.2.d', 'First Floor - Internal Ceilings', 'Supply and application of 2 layers of final coat of white Jotun fenomastic emulsion paint at internal areas — First Floor - Internal Ceilings', 'LOT', 23.00 , 23.00 ),
    ( 'G', 'G.3', 'Surface preparation using 1 coat of penetrating primer, 1 coat of stucco, sanding and supply and application & 2 layers of final coat of Jotun acrylic paint at false ceiling  at:', 'Surface preparation using 1 coat of penetrating primer, 1 coat of stucco, sanding and supply and application & 2 layers of final coat of Jotun acrylic paint at false ceiling  at:', 'LOT', NULL , NULL ),
    ( 'G', 'G.3.a', 'Powder Room', 'Surface preparation using 1 coat of penetrating primer, 1 coat of stucco, sanding and supply and application & 2 layers of final coat of Jotun acrylic paint at false ceiling  at: — Powder Room', 'LOT', 40.00 , 40.00 ),
    ( 'G', 'G.3.b', 'Maid''s Bathroom', 'Surface preparation using 1 coat of penetrating primer, 1 coat of stucco, sanding and supply and application & 2 layers of final coat of Jotun acrylic paint at false ceiling  at: — Maid''s Bathroom', 'LOT', 40.00 , 40.00 ),
    ( 'G', 'G.3.c', 'Guest Bathroom', 'Surface preparation using 1 coat of penetrating primer, 1 coat of stucco, sanding and supply and application & 2 layers of final coat of Jotun acrylic paint at false ceiling  at: — Guest Bathroom', 'LOT', 40.00 , 40.00 ),
    ( 'G', 'G.3.d', 'Common Bathroom', 'Surface preparation using 1 coat of penetrating primer, 1 coat of stucco, sanding and supply and application & 2 layers of final coat of Jotun acrylic paint at false ceiling  at: — Common Bathroom', 'LOT', 40.00 , 40.00 ),
    ( 'G', 'G.3.e', 'Bathroom 1', 'Surface preparation using 1 coat of penetrating primer, 1 coat of stucco, sanding and supply and application & 2 layers of final coat of Jotun acrylic paint at false ceiling  at: — Bathroom 1', 'LOT', 40.00 , 40.00 ),
    ( 'G', 'G.3.f', 'Master Bathroom', 'Surface preparation using 1 coat of penetrating primer, 1 coat of stucco, sanding and supply and application & 2 layers of final coat of Jotun acrylic paint at false ceiling  at: — Master Bathroom', 'LOT', 40.00 , 40.00 ),
    ( 'G', 'G.3.g', 'Kitchen', 'Surface preparation using 1 coat of penetrating primer, 1 coat of stucco, sanding and supply and application & 2 layers of final coat of Jotun acrylic paint at false ceiling  at: — Kitchen', 'LOT', 40.00 , 40.00 ),
    ( 'G', 'G.4', 'Minor repair, supply and application of 1 coat of penetrating primer, 2 coats of stucco, sanding on external walls of the villa excluding boundary wall', 'Minor repair, supply and application of 1 coat of penetrating primer, 2 coats of stucco, sanding on external walls of the villa excluding boundary wall', 'LOT', NULL , NULL ),
    ( 'G', 'G.5', 'Supply and application of 2 layers final coat of Jotashield paint at Villa Perimeter', 'Supply and application of 2 layers final coat of Jotashield paint at Villa Perimeter', 'LOT', NULL , NULL ),
    ( 'G', 'G.4-2', 'Paint touch up for the new external walls + 20cm on both sides of the perimeter with 2 layers final coat of Jotashield paint at Villa Perimeter', 'Paint touch up for the new external walls + 20cm on both sides of the perimeter with 2 layers final coat of Jotashield paint at Villa Perimeter', 'LOT', NULL , NULL ),
    ( 'G', 'G.6', 'Provisional amount for erection of scaffolding from ground floor to roof floor parapet (at 2 elevation only) of the villa to allow safe access for the external repainting works', 'Provisional amount for erection of scaffolding from ground floor to roof floor parapet (at 2 elevation only) of the villa to allow safe access for the external repainting works', 'PCS', 0.00 , 0.00 ),
    ( 'H', 'H.1', 'Closing of water supply and drainage provision of bidet at master bathroom', 'Closing of water supply and drainage provision of bidet at master bathroom', 'PCS', 205.00 , 205.00 ),
    ( 'H', 'H.2', 'Changing of the water provisions (hot / cold) new PPR & pex pipes at:', 'Changing of the water provisions (hot / cold) new PPR & pex pipes at:', 'LOT', NULL , NULL ),
    ( 'H', 'H.2.a', 'Master Bathroom - 2 vanity, shower, WC and shattaf', 'Changing of the water provisions (hot / cold) new PPR & pex pipes at: — Master Bathroom - 2 vanity, shower, WC and shattaf', 'PCS', 315.00 , 315.00 ),
    ( 'H', 'H.3', 'Relocation of water supply (hot / cold) provisions to achieve the change from bathtub to shower at master bathroom', 'Relocation of water supply (hot / cold) provisions to achieve the change from bathtub to shower at master bathroom', 'PCS', 360.00 , 360.00 ),
    ( 'H', 'H.4', 'Alignment of drainage point to achieve the change from bathtub to shower at master bathroom', 'Alignment of drainage point to achieve the change from bathtub to shower at master bathroom', 'PCS', 360.00 , 360.00 ),
    ( 'H', 'H.5', 'Installation of new water provisions (hot / cold) including chipping, repair, new PPR & pex pipes for', 'Installation of new water provisions (hot / cold) including chipping, repair, new PPR & pex pipes for', 'LOT', NULL , NULL ),
    ( 'H', 'H.6', 'Installation of new drainage point for', 'Installation of new drainage point for', 'LOT', NULL , NULL ),
    ( 'H', 'H.7', 'Installation only of  sanitary wares (WC, cistern, flush plate, shattaf, wash basin, surface mounted mixer, shower column set & bathroom accessories)', 'Installation only of  sanitary wares (WC, cistern, flush plate, shattaf, wash basin, surface mounted mixer, shower column set & bathroom accessories)', 'LOT', NULL , NULL ),
    ( 'H', 'H.7.a', 'Powder Room', 'Installation only of  sanitary wares (WC, cistern, flush plate, shattaf, wash basin, surface mounted mixer, shower column set & bathroom accessories) — Powder Room', 'PCS', 1390.00 , 1390.00 ),
    ( 'H', 'H.7.b', 'Maid''s Bathroom (shower)', 'Installation only of  sanitary wares (WC, cistern, flush plate, shattaf, wash basin, surface mounted mixer, shower column set & bathroom accessories) — Maid''s Bathroom (shower)', 'PCS', 1700.00 , 1700.00 ),
    ( 'H', 'H.7.c', 'Common Bathroom (bathtub)', 'Installation only of  sanitary wares (WC, cistern, flush plate, shattaf, wash basin, surface mounted mixer, shower column set & bathroom accessories) — Common Bathroom (bathtub)', 'PCS', 1855.00 , 1855.00 ),
    ( 'H', 'H.7.d', 'Master Bathroom (bathtub & shower)', 'Installation only of  sanitary wares (WC, cistern, flush plate, shattaf, wash basin, surface mounted mixer, shower column set & bathroom accessories) — Master Bathroom (bathtub & shower)', 'PCS', 2165.00 , 2165.00 ),
    ( 'H', 'H.7.e', 'Master Bathroom (double wash basin, bathtub & shower)', 'Installation only of  sanitary wares (WC, cistern, flush plate, shattaf, wash basin, surface mounted mixer, shower column set & bathroom accessories) — Master Bathroom (double wash basin, bathtub & shower)', 'PCS', 2350.00 , 2350.00 ),
    ( 'H', 'H.8', 'Installation only of kitchen sink and mixer including all necessary accessories.', 'Installation only of kitchen sink and mixer including all necessary accessories.', 'LOT', NULL , NULL ),
    ( 'H', 'H.4-2', 'Supply and installation of new Ariston Italy water heater (horizontally mounted). Including disconnection, dismantling and removal of existing boiler, supply and installation of new flexible hose a...', 'Supply and installation of new Ariston Italy water heater (horizontally mounted). Including disconnection, dismantling and removal of existing boiler, supply and installation of new flexible hose and angle valves', 'LOT', NULL , NULL ),
    ( 'H', 'H.7-2', 'UNDERGROUND WATER TANK:', 'UNDERGROUND WATER TANK:', 'LOT', NULL , NULL ),
    ( 'I', 'I.1', 'Installation only of LED spotlights (non-dimmable) with wiring and conduiting at false ceiling areas at:', 'Installation only of LED spotlights (non-dimmable) with wiring and conduiting at false ceiling areas at:', 'LOT', NULL , NULL ),
    ( 'I', 'I.1.a', 'Powder Room', 'Installation only of LED spotlights (non-dimmable) with wiring and conduiting at false ceiling areas at: — Powder Room', 'PCS', 205.00 , 205.00 ),
    ( 'I', 'I.1.b', 'Maid''s Bathroom', 'Installation only of LED spotlights (non-dimmable) with wiring and conduiting at false ceiling areas at: — Maid''s Bathroom', 'PCS', 205.00 , 205.00 ),
    ( 'I', 'I.1.c', 'Guest Bathroom', 'Installation only of LED spotlights (non-dimmable) with wiring and conduiting at false ceiling areas at: — Guest Bathroom', 'PCS', 205.00 , 205.00 ),
    ( 'I', 'I.1.d', 'Common Bathroom', 'Installation only of LED spotlights (non-dimmable) with wiring and conduiting at false ceiling areas at: — Common Bathroom', 'PCS', 205.00 , 205.00 ),
    ( 'I', 'I.1.e', 'Bathroom 1', 'Installation only of LED spotlights (non-dimmable) with wiring and conduiting at false ceiling areas at: — Bathroom 1', 'PCS', 205.00 , 205.00 ),
    ( 'I', 'I.1.f', 'Master Bathroom', 'Installation only of LED spotlights (non-dimmable) with wiring and conduiting at false ceiling areas at: — Master Bathroom', 'PCS', 205.00 , 205.00 ),
    ( 'I', 'I.1.g', 'Kitchen', 'Installation only of LED spotlights (non-dimmable) with wiring and conduiting at false ceiling areas at: — Kitchen', 'PCS', 205.00 , 205.00 ),
    ( 'I', 'I.2', 'Changing of single socket to double sockets including removal of existing 3x3 GI box, wall chipping, supply and installation of new 3x6 GI box with required wiring at kitchen area', 'Changing of single socket to double sockets including removal of existing 3x3 GI box, wall chipping, supply and installation of new 3x6 GI box with required wiring at kitchen area', 'PCS', 205.00 , 205.00 ),
    ( 'I', 'I.3', 'Supply and installation of non-dimmable LED strip light with acrylic diffuser and driver including necessary power provision at false ceiling of:', 'Supply and installation of non-dimmable LED strip light with acrylic diffuser and driver including necessary power provision at false ceiling of:', 'RMT', 105.00 , 105.00 ),
    ( 'I', 'I.4', 'Supply and installation of non-dimmable LED strip light with acrylic diffuser and driver including necessary power provision at Joinery items', 'Supply and installation of non-dimmable LED strip light with acrylic diffuser and driver including necessary power provision at Joinery items', 'PCS', 670.00 , 670.00 ),
    ( 'I', 'I.5', 'Installation only of hanging lights (not heavy duty) at', 'Installation only of hanging lights (not heavy duty) at', 'LOT', NULL , NULL ),
    ( 'I', 'I.6', 'Installation only of hanging lights (not heavy duty) including the necessary support, wiring and conduiting at', 'Installation only of hanging lights (not heavy duty) including the necessary support, wiring and conduiting at', 'LOT', NULL , NULL ),
    ( 'I', 'I.7', 'Installation of light provision for mirror lights / strip light at the villa', 'Installation of light provision for mirror lights / strip light at the villa', 'LOT', NULL , NULL ),
    ( 'I', 'I.8', 'Installation only of wall light including the necessary chipping, repair, wiring and conduiting at  xx', 'Installation only of wall light including the necessary chipping, repair, wiring and conduiting at  xx', 'PCS', 310.00 , 310.00 ),
    ( 'I', 'I.9', 'Cancellation of power points at living area', 'Cancellation of power points at living area', 'PCS', 155.00 , 155.00 ),
    ( 'I', 'I.10', 'Installation of power provision (including the necessary chipping, repair, wiring and conduiting) for dishwasher, microwave, oven, fridge, freezer, hob, hood and 2 double socket at Kitchen', 'Installation of power provision (including the necessary chipping, repair, wiring and conduiting) for dishwasher, microwave, oven, fridge, freezer, hob, hood and 2 double socket at Kitchen', 'PCS', 360.00 , 360.00 ),
    ( 'I', 'I.11', 'Provisional amount for removal of existing and installation of switches and socket faceplates', 'Provisional amount for removal of existing and installation of switches and socket faceplates', 'LOT', NULL , NULL ),
    ( 'I', 'I.12', 'Installation/relocation of light switches (including the necessary chipping, repair, wiring and conduiting)', 'Installation/relocation of light switches (including the necessary chipping, repair, wiring and conduiting)', 'PCS', 310.00 , 310.00 ),
    ( 'I', 'I.13', 'Relocation and alignment of gas pipeline including necessary chipping and repair', 'Relocation and alignment of gas pipeline including necessary chipping and repair', 'PCS', 1500.00 , 1500.00 ),
    ( 'I', 'I.14', 'New Gas Piping installation works with a Standardize Safety System', 'New Gas Piping installation works with a Standardize Safety System', 'LOT', NULL , NULL ),
    ( 'J', 'J.1', 'Provisional amount for AC Ducts Cleaning: Filter, Grill, Vent, Air Supply and Return, Flushing Drain Line and Spray Antibacterial Treatment', 'Provisional amount for AC Ducts Cleaning: Filter, Grill, Vent, Air Supply and Return, Flushing Drain Line and Spray Antibacterial Treatment', 'PCS', 480.00 , 480.00 ),
    ( 'J', 'J.2', 'Provisional amount for Air Conditioning Deep Cleaning: Evaporator coil cleaning and blower fan motor and programming', 'Provisional amount for Air Conditioning Deep Cleaning: Evaporator coil cleaning and blower fan motor and programming', 'PCS', 830.00 , 830.00 ),
    ( 'J', 'J.2-2', 'Supply and installation of normal plain white linear grill including removal of existing at the Villa', 'Supply and installation of normal plain white linear grill including removal of existing at the Villa', 'LOT', NULL , NULL ),
    ( 'J', 'J.3', 'Preparation of HVAC design layout for the proposed new ACU and new AC PI Ducts', 'Preparation of HVAC design layout for the proposed new ACU and new AC PI Ducts', 'PCS', 4200.00 , 4200.00 ),
    ( 'J', 'J.3-2', 'Supply and installation of 2.0 ton Split AC indoor and outdoor unit with exposed PVC trucking at Guest Bathroom. Including the power provision of indoor and outdoor unit.', 'Supply and installation of 2.0 ton Split AC indoor and outdoor unit with exposed PVC trucking at Guest Bathroom. Including the power provision of indoor and outdoor unit.', 'PCS', 5800.00 , 5800.00 )
) AS v(
    master_code,
    work_item_code,
    work_item_name,
    description,
    unit_type,
    default_rate,
    cost_price
)
JOIN work_item_masters wim
  ON wim.company_id = c.uuid
 AND wim.code = v.master_code
ON CONFLICT (company_id, work_item_code) DO NOTHING;
